[2024-08-14T11:45:58.670+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T11:45:58.680+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver-finance-pipeline.process_naver_finance manual__2024-08-14T02:45:54.387603+00:00 [queued]>
[2024-08-14T11:45:58.683+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver-finance-pipeline.process_naver_finance manual__2024-08-14T02:45:54.387603+00:00 [queued]>
[2024-08-14T11:45:58.683+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T11:45:58.697+0900] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_naver_finance> on 2024-08-14 02:45:54.387603+00:00
[2024-08-14T11:45:58.700+0900] {standard_task_runner.py:64} INFO - Started process 12314 to run task
[2024-08-14T11:45:58.702+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'naver-finance-pipeline', 'process_naver_finance', 'manual__2024-08-14T02:45:54.387603+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/soup-pipeline.py', '--cfg-path', '/tmp/tmpgd1of67v']
[2024-08-14T11:45:58.702+0900] {standard_task_runner.py:91} INFO - Job 25: Subtask process_naver_finance
[2024-08-14T11:45:58.730+0900] {task_command.py:426} INFO - Running <TaskInstance: naver-finance-pipeline.process_naver_finance manual__2024-08-14T02:45:54.387603+00:00 [running]> on host demo-server
[2024-08-14T11:45:58.773+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='naver-finance-pipeline' AIRFLOW_CTX_TASK_ID='process_naver_finance' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T02:45:54.387603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T02:45:54.387603+00:00'
[2024-08-14T11:45:58.774+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T11:45:58.781+0900] {logging_mixin.py:188} INFO - [[{'c_name': '미국 USD', 'exchange_rate': '1,360.10', 'change': ' 4.90', 'updown': '하락'}, {'c_name': '일본 JPY(100엔)', 'exchange_rate': '929.70', 'change': ' 0.36', 'updown': '하락'}, {'c_name': '유럽연합 EUR', 'exchange_rate': '1,494.95', 'change': ' 6.07', 'updown': '하락'}, {'c_name': '중국 CNY', 'exchange_rate': '190.33', 'change': ' 0.63', 'updown': '하락'}]]
[2024-08-14T11:45:58.783+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T11:45:58.783+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/soup-pipeline.py", line 26, in _processing_result
    processed_documents.to_csv("/home/ubuntu/airflow/tmp/naver_result.csv", index=None, header=False)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/pandas/core/generic.py", line 3721, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1189, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/pandas/io/common.py", line 735, in get_handle
    check_parent_directory(str(handle))
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/pandas/io/common.py", line 598, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/ubuntu/airflow/tmp'
[2024-08-14T11:45:58.788+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=naver-finance-pipeline, task_id=process_naver_finance, run_id=manual__2024-08-14T02:45:54.387603+00:00, execution_date=20240814T024554, start_date=20240814T024558, end_date=20240814T024558
[2024-08-14T11:45:58.801+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task process_naver_finance (Cannot save file into a non-existent directory: '/home/ubuntu/airflow/tmp'; 12314)
[2024-08-14T11:45:58.839+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-14T11:45:58.846+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T11:45:58.847+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
